version: '3.9'
services:
  qwen32b:
    image: ganxing/v0.3.3_modelscope
    command: --model Qwen/Qwen1.5-32B-Chat-AWQ --tokenizer Qwen/Qwen1.5-32B-Chat --max-model-len 2200 --enforce-eager --gpu-memory-utilization 0.99 --served-model gpt-3.5-turbo
    environment:
      - VLLM_USE_MODELSCOPE=True
    volumes:
      - /home/nobody/.cache/modelscope:/root/.cache/modelscope
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ['gpu']

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    container_name: chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      - BASE_URL=http://qwen32b:8000
    depends_on:
      - qwen32b

networks:
  default:
    driver: bridge
